import type { Property } from "./property-types";

/**
 * Demo records use address, bedroom, bathroom, land-area, valuation and
 * coordinate fields from the public Auckland Housing Market dataset:
 * https://github.com/Sakyawira/auckland-house-prices
 *
 * Property category, style, floor area, building age, flood band, aspect,
 * sunlight and recent sale dates are clearly-labelled product demo enrichments.
 * Photography is downloaded from Unsplash and is illustrative rather than a
 * photograph of the named address.
 */
export const properties: Property[] = [
  {
    id: "kelmarna-avenue",
    address: "54 Kelmarna Avenue",
    suburb: "Ponsonby",
    city: "Auckland",
    region: "Auckland",
    price: 2_525_000,
    bedrooms: 3,
    bathrooms: 1,
    landArea: 531,
    floorArea: 148,
    yearBuilt: 1912,
    propertyType: "Villa",
    architecturalStyle: "Character",
    floodRisk: "Moderate",
    orientation: "East",
    sunlightHours: 5.4,
    latitude: -36.8492389,
    longitude: 174.7344513,
    image: "/properties/villa-greylynn.jpg",
    imageAlt: "White character home with a pool and subtropical garden",
  },
  {
    id: "costa-viva-crescent",
    address: "43 Costa Viva Crescent",
    suburb: "Karaka",
    city: "Auckland",
    region: "Auckland",
    price: 810_000,
    bedrooms: 3,
    bathrooms: 2,
    landArea: 220,
    floorArea: 142,
    yearBuilt: 2020,
    propertyType: "Townhouse",
    architecturalStyle: "Modernist",
    floodRisk: "Low",
    orientation: "North",
    sunlightHours: 7.8,
    latitude: -37.0775661,
    longitude: 174.9201295,
    image: "/properties/townhouse-karaka.jpg",
    imageAlt: "Modern dark timber home opening to a landscaped garden",
  },
  {
    id: "ascot-avenue",
    address: "34A Ascot Avenue",
    suburb: "Remuera",
    city: "Auckland",
    region: "Auckland",
    price: 1_220_000,
    bedrooms: 3,
    bathrooms: 1,
    landArea: 279,
    floorArea: 115,
    yearBuilt: 1968,
    propertyType: "Apartment",
    architecturalStyle: "Mid-Century",
    floodRisk: "Low",
    orientation: "North",
    sunlightHours: 7.1,
    latitude: -36.8839242,
    longitude: 174.8026025,
    image: "/properties/apartment-remuera.jpg",
    imageAlt: "Sunlit contemporary open-plan dining room",
  },
  {
    id: "rawhiti-road",
    address: "39 Rawhiti Road",
    suburb: "One Tree Hill",
    city: "Auckland",
    region: "Auckland",
    price: 1_400_000,
    bedrooms: 3,
    bathrooms: 2,
    landArea: 1_024,
    floorArea: 176,
    yearBuilt: 1936,
    propertyType: "House",
    architecturalStyle: "Craftsman",
    floodRisk: "Moderate",
    orientation: "West",
    sunlightHours: 6.2,
    latitude: -36.9077,
    longitude: 174.7960425,
    image: "/properties/house-onetreehill.jpg",
    imageAlt: "Craftsman-style home with a broad veranda and lawn",
  },
  {
    id: "pulham-road",
    address: "122 Pulham Road",
    suburb: "Warkworth",
    city: "Auckland",
    region: "Auckland",
    price: 890_000,
    bedrooms: 4,
    bathrooms: 2,
    landArea: 1_513,
    floorArea: 187,
    yearBuilt: 2004,
    propertyType: "Lifestyle block",
    architecturalStyle: "Contemporary",
    floodRisk: "Low",
    orientation: "North",
    sunlightHours: 8.1,
    latitude: -36.409687,
    longitude: 174.6729053,
    image: "/properties/lifestyle-warkworth.jpg",
    imageAlt: "Detached home beneath a clear blue sky",
  },
  {
    id: "sussex-street",
    address: "10 Sussex Street",
    suburb: "Grey Lynn",
    city: "Auckland",
    region: "Auckland",
    price: 2_275_000,
    bedrooms: 4,
    bathrooms: 3,
    landArea: 480,
    floorArea: 192,
    yearBuilt: 1908,
    propertyType: "Villa",
    architecturalStyle: "Character",
    floodRisk: "Low",
    orientation: "North",
    sunlightHours: 7.4,
    latitude: -36.8625187,
    longitude: 174.7474227,
    image: "/properties/house-onetreehill.jpg",
    imageAlt: "Character home with veranda and mature garden",
  },
  {
    id: "richmond-road",
    address: "59/386 Richmond Road",
    suburb: "Grey Lynn",
    city: "Auckland",
    region: "Auckland",
    price: 720_000,
    bedrooms: 3,
    bathrooms: 2,
    landArea: 130,
    floorArea: 104,
    yearBuilt: 2016,
    propertyType: "Apartment",
    architecturalStyle: "Contemporary",
    floodRisk: "High",
    orientation: "South",
    sunlightHours: 4.2,
    latitude: -36.8563101,
    longitude: 174.730722,
    image: "/properties/apartment-greylynn.jpg",
    imageAlt: "Angular contemporary home clad in timber and black metal",
  },
  {
    id: "musson-drive",
    address: "11 Musson Drive",
    suburb: "Waiheke Island",
    city: "Auckland",
    region: "Auckland",
    price: 1_975_000,
    bedrooms: 4,
    bathrooms: 3,
    landArea: 240,
    floorArea: 168,
    yearBuilt: 2019,
    propertyType: "House",
    architecturalStyle: "Modernist",
    floodRisk: "Moderate",
    orientation: "North",
    sunlightHours: 8.4,
    latitude: -36.8115438,
    longitude: 175.0832685,
    image: "/properties/villa-ponsonby.jpg",
    imageAlt: "Crisp modern home with timber screens and a green lawn",
  },
  {
    id: "belmont-place",
    address: "10 Belmont Place",
    suburb: "Warkworth",
    city: "Auckland",
    region: "Auckland",
    price: 830_000,
    bedrooms: 3,
    bathrooms: 2,
    landArea: 606,
    floorArea: 139,
    yearBuilt: 1974,
    propertyType: "House",
    architecturalStyle: "Mid-Century",
    floodRisk: "Low",
    orientation: "East",
    sunlightHours: 6.6,
    latitude: -36.3955453,
    longitude: 174.6535508,
    image: "/properties/warkworth-house.jpg",
    imageAlt: "Bright open-plan living room with timber staircase",
  },
  {
    id: "hardington-street",
    address: "2/30 Hardington Street",
    suburb: "Onehunga",
    city: "Auckland",
    region: "Auckland",
    price: 740_000,
    bedrooms: 2,
    bathrooms: 1,
    landArea: 65,
    floorArea: 88,
    yearBuilt: 2018,
    propertyType: "Townhouse",
    architecturalStyle: "Contemporary",
    floodRisk: "High",
    orientation: "West",
    sunlightHours: 4.8,
    latitude: -36.9129965,
    longitude: 174.7874249,
    image: "/properties/onehunga-home.jpg",
    imageAlt: "Contemporary interior overlooking a compact pool terrace",
  },
];

export const comparableSales: Property[] = [
  {
    ...properties[0],
    id: "sale-clarence-street",
    address: "51 Clarence Street",
    price: 1_625_000,
    bedrooms: 2,
    floorArea: 132,
    latitude: -36.8481167,
    longitude: 174.73943,
    soldDate: "2026-08-12",
  },
  {
    ...properties[0],
    id: "sale-jervois-road",
    address: "268 Jervois Road",
    price: 2_275_000,
    floorArea: 156,
    latitude: -36.8474028,
    longitude: 174.7324135,
    soldDate: "2026-05-21",
  },
  {
    ...properties[0],
    id: "sale-waima-street",
    address: "12 Waima Street",
    price: 2_180_000,
    bedrooms: 4,
    floorArea: 174,
    latitude: -36.8635176,
    longitude: 174.7506549,
    soldDate: "2026-04-04",
  },
  {
    ...properties[1],
    id: "sale-kuhanui-drive",
    address: "45 Kuhanui Drive",
    price: 1_025_000,
    floorArea: 160,
    latitude: -37.0779534,
    longitude: 174.9188179,
    soldDate: "2026-07-28",
  },
  {
    ...properties[1],
    id: "sale-wawatai-drive",
    address: "8 Wawatai Drive",
    price: 1_175_000,
    bedrooms: 4,
    floorArea: 171,
    latitude: -37.0800841,
    longitude: 174.9260771,
    soldDate: "2026-06-10",
  },
  {
    ...properties[2],
    id: "sale-monteith-crescent",
    address: "11D Monteith Crescent",
    price: 880_000,
    floorArea: 102,
    latitude: -36.8815435,
    longitude: 174.8228154,
    soldDate: "2026-08-02",
  },
  {
    ...properties[3],
    id: "sale-grey-street",
    address: "152 Grey Street",
    price: 1_175_000,
    bedrooms: 4,
    floorArea: 184,
    latitude: -36.9175628,
    longitude: 174.7935673,
    soldDate: "2026-05-14",
  },
  {
    ...properties[4],
    id: "sale-belmont-place",
    address: "10 Belmont Place",
    price: 830_000,
    bedrooms: 3,
    floorArea: 162,
    latitude: -36.3955453,
    longitude: 174.6535508,
    soldDate: "2026-07-03",
  },
  {
    ...properties[6],
    id: "sale-great-north-road",
    address: "556 Great North Road",
    price: 1_575_000,
    floorArea: 112,
    latitude: -36.8659995,
    longitude: 174.7375053,
    soldDate: "2026-06-23",
  },
  {
    ...properties[9],
    id: "sale-pleasant-street",
    address: "25C Pleasant Street",
    price: 990_000,
    bedrooms: 3,
    floorArea: 109,
    latitude: -36.9198143,
    longitude: 174.7722528,
    soldDate: "2026-08-19",
  },
];
